version: "3"

volumes:
  dbdata:

services:

  # テスト用のDB：
  userdata:
    image: mysql:5.7.24
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_USER=user
      - MYSQL_DATABASE=test
      - MYSQL_PASSWORD=secret
      - TZ=Asia/Tokyo
    ports:
      - "33061:3306"
    volumes:
      - dbdata:/var/lib/mysql